version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.8-stretch
    working_directory: /go/src/github.com/ncabatoff/process-exporter
    steps:
      - checkout
      - run: make style vet test build integ
  image:
    docker:
      - image: docker:stable-git
    working_directory: /go/src/github.com/ncabatoff/process-exporter
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t ncabatoff/process-exporter:latest .

workflows:
  version: 2
  build_and_image:
    jobs:
      - build
      - image
